; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "JpegCompressorCS"
#define MyAppVersion "1.3.1"
#define MyAppPublisher "Surratt Solutions"
#define MyAppURL "https://www.surrattsolutions.com/"
#define MyAppExeName "JpegCompressorCS.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9E2D10EE-03CD-43D8-9A85-FE88E04BE76A}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
AppCopyright=Copyright (C) 2026 Surratt Solutions
VersionInfoCopyright=Copyright (C) 2026 Surratt Solutions
VersionInfoVersion=1.3.1.0
DefaultDirName={autopf32}\SurrattSolutions\{#MyAppName}
UsePreviousAppDir=no
UninstallDisplayIcon={app}\{#MyAppExeName}
UninstallDisplayName=JpegCompressorCS (32-bit)
DisableProgramGroupPage=yes
LicenseFile=C:\Users\tron\source\repos\JpegCompressor\LICENSE.txt
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir=C:\Users\tron\source\repos\JpegCompressorCS\bin\Release\win-x86
OutputBaseFilename=JpegCompressorCS-x86-setup
SetupIconFile=C:\Users\tron\source\repos\JpegCompressorCS\JpegCompressor.ico
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\tron\source\repos\JpegCompressorCS\bin\Release\win-x86\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

